create table if not exists findren_hp_member(
    fhm_type int,
    fhm_id varchar(20) primary key,
    fhm_pw varchar(20),
    fhm_name varchar(10),
    fhm_sex varchar(2),
    fhm_per_nation varchar(5),
    fhm_per_email varchar(25),
    fhm_per_birth varchar(14),
    fhm_per_phone varchar(15),
    fhm_per_cell varchar(15),
    fhm_com_part varchar(10),
    fhm_com_nation varchar(5),
    fhm_com_name varchar(30),
    fhm_com_logo varchar(30),
    fhm_com_no varchar(20),
    fhm_com_style varchar(10),
    fhm_com_biz varchar(30),
    fhm_com_ceo varchar(10),
    fhm_com_emp varchar(10),
    fhm_com_birth varchar(14),
    fhm_com_homepage varchar(50),
    fhm_com_phone varchar(15),
    fhm_com_email varchar(25),
    fhm_mailig varchar(2),
    fhm_noauth varchar(10)
);